<a href="https://colab.research.google.com/github/VikasAL/Python_Workshop/blob/master/Day3_Session2_Numpy_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Write a NumPy program to generate five random numbers from the normal distribution.

In [1]:
import numpy as np
x = np.random.normal(size=5)
print(x)


[ 0.3308058  -0.60716213 -0.49212906  0.28782376 -0.67137192]


#Write a NumPy program to generate six random integers between 10 and 30

In [2]:
import numpy as np
x = np.random.randint(low=10, high=30, size=6)
print(x)


[26 17 12 16 12 15]


#Write a NumPy program to create a 3x3x3 array with random values.

In [3]:
import numpy as np
x = np.random.random((3,3,3))
print(x)


[[[0.86407242 0.2070341  0.7930128 ]
  [0.24549264 0.43945017 0.08939657]
  [0.28899437 0.03290469 0.07622957]]

 [[0.02447111 0.34835169 0.42111711]
  [0.97722285 0.77599381 0.76892462]
  [0.2351124  0.32788022 0.46890272]]

 [[0.47049078 0.05140341 0.02094047]
  [0.91444939 0.7623684  0.18098034]
  [0.71094227 0.77125921 0.035042  ]]]


#Write a NumPy program to create a 5x5 array with random values and find the minimum #and maximum values.

In [4]:
import numpy as np
x = np.random.random((5,5))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.45168891 0.23953162 0.45361207 0.96061597 0.43742525]
 [0.83305422 0.80489994 0.07572522 0.53474735 0.34008523]
 [0.99301811 0.09119691 0.70073415 0.40961932 0.16615303]
 [0.44643358 0.11400821 0.12799687 0.86541545 0.76250424]
 [0.92297868 0.48222481 0.76418403 0.56212562 0.57121165]]
Minimum and Maximum Values:
0.0757252182867525 0.9930181127824806


#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [5]:
import numpy as np
x = np.random.rand(10, 4)
print("Original array: ")
print(x)
y= x[:5, :]
print("First 5 rows of the above array:")
y= x[:5, :]
print(y)
z= x[:, :4]
print("First 3 columns of the above array:")
print(z)


Original array: 
[[0.25771551 0.64855154 0.52281681 0.27493982]
 [0.90485567 0.02802533 0.43215649 0.29731404]
 [0.69337487 0.33713004 0.12205025 0.90608528]
 [0.33713088 0.2031164  0.13797393 0.4572129 ]
 [0.40947603 0.87432531 0.53370607 0.65488055]
 [0.95463565 0.93212263 0.12026655 0.06320258]
 [0.25752147 0.80082919 0.63117382 0.9436643 ]
 [0.6796725  0.41434852 0.53292198 0.58143673]
 [0.35497501 0.42852025 0.55546478 0.08296796]
 [0.60311058 0.25836852 0.20195624 0.21829241]]
First 5 rows of the above array:
[[0.25771551 0.64855154 0.52281681 0.27493982]
 [0.90485567 0.02802533 0.43215649 0.29731404]
 [0.69337487 0.33713004 0.12205025 0.90608528]
 [0.33713088 0.2031164  0.13797393 0.4572129 ]
 [0.40947603 0.87432531 0.53370607 0.65488055]]
First 3 columns of the above array:
[[0.25771551 0.64855154 0.52281681 0.27493982]
 [0.90485567 0.02802533 0.43215649 0.29731404]
 [0.69337487 0.33713004 0.12205025 0.90608528]
 [0.33713088 0.2031164  0.13797393 0.4572129 ]
 [0.40947603 0.8743

#Write a NumPy program to shuffle numbers and find permutation  between 0 and 10 #(inclusive).

In [6]:
import numpy as np
x = np.arange(10)
np.random.shuffle(x)
print(x)
print("Same result using permutation():")
print(np.random.permutation(10))


[7 6 4 2 1 5 9 3 8 0]
Same result using permutation():
[1 4 3 7 6 5 2 0 9 8]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [11]:
import numpy as np
x=np.arange(10)
np.random.randint(1, size=x)
print (x)


[0 1 2 3 4 5 6 7 8 9]


#Write a NumPy program to create a random integer nos of size 10 and sort it.

In [9]:
import numpy as np
x=np.arange(10)
np.random.shuffle(x)
print(x)
x.sort()
print(x)


[4 2 5 3 7 9 1 6 0 8]
[0 1 2 3 4 5 6 7 8 9]
